version: "3.8"

services:

  accounts:
    image: anadwi/accounts
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - anadwi-network
    
  loans:
    image: anadwi/loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - anadwi-network
    
  cards:
    image: anadwi/cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - anadwi-network
    
networks:
  anadwi-network: